### ISSUE TITLE
Switch English copy to German copy

### ISSUE THREAD

**Issue by ambrwlsn** [lovelysystems/lovely-editor#28]
https://github.com/lovelysystems/oyez-editor/blob/fae92648b2d64005f389679fd9a262b5c2b291ef/src/components/editor-quill/index.js#L132

Switch placeholder text from ”Write a text...” to “Bitte fügen Sie hier den Text ein…”

**Comment by natterstefan** [comment]
Closed, as we will implement react-intl at a later point.
